### ISSUE TITLE
sbt reload fails

### ISSUE THREAD

**Issue by mgilbertnz** [stonexx/sbt-webpack#4]
Hi there,

Thanks for writing this plugin, it's saved me heaps of time.  I think I may have found an issue with the watch feature.

The issue occurs when I try to reload an sbt play project with this plugin added.  I don't have any sbt-webpack specific settings in my build.sbt.  I tested and this issue also occurs with sbt-play-webpack.

```
src$ sbt
[server-play] $ reload
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:313)
        at scala.None$.get(Option.scala:311)
        at com.github.stonexx.sbt.webpack.SbtWebpack$autoImport$.stateToWebpackWatcherRunner(SbtWebpack.scala:60)
```
[full-stack-trace.txt](https://github.com/stonexx/sbt-webpack/files/965909/full-stack-trace.txt)

I've forked this project and removed the watch feature as I don't need it and reload works with it removed.

Cheers,

Matt

**Comment by stonexx** [comment]
This problem did not happen with the `sbt-webpack-tester` project with `sbt-webpack` latest version.

What version of the plug-in was used?

Please provide test  project files and environment informations.

thx.
